### ISSUE TITLE
压测报错PerformanceDMC group0 4 100 100

### ISSUE THREAD

**Issue by helloHKTK** [FISCO-BCOS/java-sdk-demo#204]
[root@ddd dist]# java -cp 'conf/:lib/*:apps/*' org.fisco.bcos.sdk.demo.perf.PerformanceDMC group0 4 100 100
====== Start test, user count: 4, count: 100, qps:100, groupId: group0
Create account...
ContractException{responseOutput=null, errorCode=18}
        at org.fisco.bcos.sdk.v3.transaction.codec.decode.ReceiptParser.getErrorStatus(ReceiptParser.java:72)
        at org.fisco.bcos.sdk.v3.contract.Contract.deploy(Contract.java:211)
        at org.fisco.bcos.sdk.demo.contract.Account.deploy(Account.java:207)
        at org.fisco.bcos.sdk.demo.perf.PerformanceDMC.lambda$start$0(PerformanceDMC.java:119)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
ContractException{responseOutput=null, errorCode=18}
        at org.fisco.bcos.sdk.v3.transaction.codec.decode.ReceiptParser.getErrorStatus(ReceiptParser.java:72)
        at org.fisco.bcos.sdk.v3.contract.Contract.deploy(Contract.java:211)
        at org.fisco.bcos.sdk.demo.contract.Account.deploy(Account.java:207)
        at org.fisco.bcos.sdk.demo.perf.PerformanceDMC.lambda$start$0(PerformanceDMC.java:119)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
ContractException{responseOutput=null, errorCode=18}
        at org.fisco.bcos.sdk.v3.transaction.codec.decode.ReceiptParser.getErrorStatus(ReceiptParser.java:72)
        at org.fisco.bcos.sdk.v3.contract.Contract.deploy(Contract.java:211)
        at org.fisco.bcos.sdk.demo.contract.Account.deploy(Account.java:207)
        at org.fisco.bcos.sdk.demo.perf.PerformanceDMC.lambda$start$0(PerformanceDMC.java:119)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.IntPipeline.forEach(IntPipeline.java:427)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:584)
        at org.fisco.bcos.sdk.demo.perf.PerformanceDMC.start(PerformanceDMC.java:111)
        at org.fisco.bcos.sdk.demo.perf.PerformanceDMC.main(PerformanceDMC.java:73)
ContractException{responseOutput=null, errorCode=18}
        at org.fisco.bcos.sdk.v3.transaction.codec.decode.ReceiptParser.getErrorStatus(ReceiptParser.java:72)
        at org.fisco.bcos.sdk.v3.contract.Contract.deploy(Contract.java:211)
        at org.fisco.bcos.sdk.demo.contract.Account.deploy(Account.java:207)
        at org.fisco.bcos.sdk.demo.perf.PerformanceDMC.lambda$start$0(PerformanceDMC.java:119)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Create account finished!
Sending transactions...
java.lang.NullPointerException
        at org.fisco.bcos.sdk.demo.perf.PerformanceDMC.lambda$start$1(PerformanceDMC.java:162)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
        at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateParallel(ForEachOps.java:188)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.IntPipeline.forEach(IntPipeline.java:427)
        at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:584)
        at org.fisco.bcos.sdk.demo.perf.PerformanceDMC.start(PerformanceDMC.java:152)
        at org.fisco.bcos.sdk.demo.perf.PerformanceDMC.main(PerformanceDMC.java:73)
[root@datd ddd]#

**Comment by kyonRay** [comment]
错误码是18，可能和链上部署合约的权限控制有关。

**Comment by helloHKTK** [comment]
我开启了白名单模式，我该怎么配置java-sdk-demo，才能正常运行压测代码？
```
[group0]: /apps> getDeployAuth
Deploy strategy is White List Access.
```

> 错误码是18，可能和链上部署合约的权限控制有关。

**Comment by helloHKTK** [comment]
> 我开启了白名单模式，我该怎么配置java-sdk-demo，才能正常运行压测代码？
> 
> ```
> [group0]: /apps> getDeployAuth
> Deploy strategy is White List Access.
> ```
> 
> > 错误码是18，可能和链上部署合约的权限控制有关。

问题解决了，由于我当前的部署权限为白名单模式，检查发现账户0x232ce82802dec5b15a8d6e65a98e1d529beabee2有权限部署，因此在dist目录下新建文件夹dist>account>ecdsa，然后把0x232ce82802dec5b15a8d6e65a98e1d529beabee2.pem放到了ecdsa文件中，然后修改dist>conf>config.toml，修改`accountAddress = 0x232ce82802dec5b15a8d6e65a98e1d529beabee2`，重新运行问题解决
```
[group0]: /apps> getDeployAuth
Deploy strategy is White List Access.

[group0]: /apps> checkDeployAuth
Deploy : PERMISSION DENIED
Account: 0x34d56a661e41a7488c5274a337753add3d533123

[group0]: /apps> listAccount
0x34d56a661e41a7488c5274a337753add3d533123(current account) <=
0x232ce82802dec5b15a8d6e65a98e1d529beabee2


[group0]: /apps> loadAccount 0x232ce82802dec5b15a8d6e65a98e1d529beabee2
Load account 0x232ce82802dec5b15a8d6e65a98e1d529beabee2 success!

[group0]: /apps> checkDeployAuth
Deploy : ACCESS
Account: 0x232ce82802dec5b15a8d6e65a98e1d529beabee2
```
